# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 928c45a9c2ef2a02d77db087ccae16138e143284f4d01bc734d2ad039627bd8feed2eb812a3b4bd19c3dc9a633305a68cca824cbac65bbaa29f0a949a7bf2f81

test:
  secret_key_base: e9dcb83c8ea78c180ad589d7f50c20f734205b848db24211318bb904a320f1a131bbd7d98ae1d00c402d11059db0082063d2ebe4e3d887556bfc03e66a464b37

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
